### ISSUE TITLE
LimeSuiteGUI crashes

### ISSUE THREAD

**Issue by keithbriggs** [myriadrf/LimeSDR_Workshop#2]
On Ubuntu 14 and 16, Lime_Suite consistently crashes with a segfault immediately after loading a .ini file.  This means nothing useful can be done with it.

**Comment by MatthewonCODE** [comment]
That was using the pre-compiled version.   When we compile it ourselves, we get:

Thread 1 "LimeSuiteGUI" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b4d4a5 in std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/local/lib/libLimeSuite.so.17.07-1

**Comment by 9600** [comment]
If you are still experiencing this problem after updating I would be grateful if you could raise an issue on the Lime Suite tracker.

https://github.com/myriadrf/LimeSuite
