### ISSUE TITLE
source and sink are in different processes

### ISSUE THREAD

**Issue by guruofquality** [myriadrf/LimeSDR_Workshop#3]
https://github.com/myriadrf/LimeSDR_Workshop/blob/0ec891047b2552743d083c204a154187c75a1c74/pothos/LimeTxRxDemo.pothos#L10

The source and sink are in different processes, this was causing an issue. I didnt have push access, but could we make this line an empty string, so "gui" to ""?

**Comment by 9600** [comment]
Added access — forgot to add Core team.

**Comment by guruofquality** [comment]
Thanks, pushed!
